### PR TITLE
Use a Makefile and introduce .pre-commit

### PR DESCRIPTION
**Pull request by tschm**

### CODE REVIEW

**Comment by tschm** [comment]
This will be a github action soon. For now, please try 

make install

or 

make fmt

or 

make jupyter

or just

make

**Comment by tschm** [comment]
@jonathan-taylor Makefiles can help a great deal to simplify tasks such as installing or the construction of images

**Comment by jonathan-taylor** [comment]
> @jonathan-taylor Makefiles can help a great deal to simplify tasks such as installing or the construction of images

Thanks, I am aware of `make`.

- `pre-commit` could be useful
- not sure why this needs to be a github action. 
- the `jupyter` and `book` targets seem unnecessary

**Comment by tschm** [comment]
the book target is commented out. I may revisit at a later stage. 
A github action can confirm that the repo is in good shape (as defined via ruff etc)
The jupyter action just install jupyterlab if it not there already...

**Comment by jonathan-taylor** [comment]
I'm going to close this because this repo isn't the place for a Makefile. This is where students will land, no need to confuse them with a Makefile.

**Pull request closed without merging**
